name: Run Jupyter Notebook

on:
  push:
    paths:
      - '*.ipynb'

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install jupyter numpy opencv-python matplotlib sklearn scipy wandb
          
      - name: Run notebook
        run: |
          jupyter nbconvert --to notebook --execute 'Lab 5-Spring 2025.ipynb'
          
      - name: Upload notebook
        uses: actions/upload-artifact@v4
        with:
          name: notebook-output
          path: 'notebook_output.ipynb'
